# -*- coding: utf-8 -*-
"""titanicEDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IkRaFlOS2etghWcpujUJXx_cJHeMnEnF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train =  pd.read_csv("")

from google.colab import files

# Upload your CSV file
uploaded = files.upload()

# Assuming you uploaded 'my_data.csv'
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# Display the first 5 rows of the DataFrame
display(df.head())

#finding null values
df.isnull()

sns.heatmap(df.isnull(),yticklabels=False,cbar=False,cmap='viridis')

sns.set_style('whitegrid')
sns.countplot(x='Survived',data=df)

sns.set_style("whitegrid")
sns.countplot(x="Survived", hue='Sex', data = df, palette='RdBu_r')

sns.set_style('whitegrid')
sns.countplot(x='Survived',hue='Pclass', data=df, palette='rainbow')

sns.distplot(df['Age'].dropna(),kde=False,color='darkred',bins=40)

df['Age'].hist(bins=30,color='darkred',alpha=0.3)

sns.countplot(x='SibSp',data=df)

df['Fare'].hist(color='green',bins=40,figsize=(10,4))

plt.figure(figsize=(12,7))
sns.boxplot(x='Pclass', y='Age',data=df, palette='winter')

def impute_age(cols):
  Age = cols.iloc[0]
  Pclass = cols.iloc[1]
  if pd.isnull(Age):
    if Pclass ==1:
      return 37
    elif Pclass==2:
      return 29
    else:
      return 24
  else:
    return Age

df['Age'] = df[['Age', 'Pclass']].apply(impute_age,axis=1)

sns.heatmap(df.isnull(),yticklabels=False,cbar=False,cmap='viridis')

df.drop('Cabin',axis=1,inplace=True)

sns.heatmap(df.isnull(),yticklabels=False,cbar=False,cmap='viridis')

pd.get_dummies(df['Embarked'],drop_first=True).head()

sex = pd.get_dummies(df['Sex'],drop_first=True)
embark=pd.get_dummies(df['Embarked'],drop_first=True)

df.drop(['Sex','Embarked','Name','Ticket'],axis=1,inplace=True)

df.head()

df=pd.concat([df,sex,embark],axis=1)

df.drop('Survived',axis=1).head()

df['Survived'].head()

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df.drop('Survived',axis=1),df['Survived'],test_size=0.30,random_state=101)

"""### Fixing `NaN` values and re-preparing data for modeling

The `ValueError` from `LogisticRegression` indicates that the training data still contains `NaN` (Not a Number) values. This is likely due to issues during the previous data cleaning and feature engineering steps, such as incorrect column drops or repeated concatenations that introduced `NaN`s or duplicate columns.

To address this, we will re-execute the data preparation from a fresh start, ensuring all `NaN` values are handled and the feature set is correctly structured before splitting the data into training and testing sets.
"""

# Re-load the original data to ensure a clean DataFrame state
df_clean = pd.read_csv(file_name)

# Re-apply age imputation
df_clean['Age'] = df_clean[['Age', 'Pclass']].apply(impute_age, axis=1)

# Drop the 'Cabin' column as it has too many missing values
df_clean.drop('Cabin', axis=1, inplace=True)

# Create dummy variables for 'Sex' and 'Embarked' before dropping original columns
sex_dummies = pd.get_dummies(df_clean['Sex'], drop_first=True, dtype=int)
embark_dummies = pd.get_dummies(df_clean['Embarked'], drop_first=True, dtype=int)

# Drop the original categorical columns and non-useful identifier columns
df_clean.drop(['Sex', 'Embarked', 'Name', 'Ticket', 'PassengerId'], axis=1, inplace=True)

# Concatenate the new dummy variables to the DataFrame
df_clean = pd.concat([df_clean, sex_dummies, embark_dummies], axis=1)

# Verify that there are no remaining NaN values in the features
print("\nMissing values after cleaning:")
print(df_clean.isnull().sum())

display(df_clean.head())

"""Now that the data is clean and prepared, we can split it into training and testing sets again."""

# Re-perform train-test split with the cleaned DataFrame
X = df_clean.drop('Survived', axis=1)
y = df_clean['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

from sklearn.linear_model import LogisticRegression

logmodel=LogisticRegression(max_iter=1000) # Increased max_iter for convergence if needed
logmodel.fit(X_train,y_train)

predictions = logmodel.predict(X_test)

from sklearn.metrics import confusion_matrix, classification_report

accuracy=confusion_matrix(y_test,predictions)

accuracy

from sklearn.metrics import accuracy_score

accuracy_score(y_test,predictions)

print(classification_report(y_test,predictions))

"""### Visualizing the Confusion Matrix"""

plt.figure(figsize=(6, 4))
sns.heatmap(accuracy, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No', 'Predicted Yes'],
            yticklabels=['Actual No', 'Actual Yes'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

"""### Feature Engineering: Extracting Titles from 'Name'"""

import re

# Re-load the original data to ensure a clean DataFrame state before new feature engineering
df_feature_eng = pd.read_csv(file_name)

# Apply age imputation first, as it's a critical preprocessing step
df_feature_eng['Age'] = df_feature_eng[['Age', 'Pclass']].apply(impute_age, axis=1)

# Function to extract titles
def get_title(name):
    title_search = re.search(' ([A-Za-z]+)\.', name)
    # If the title exists, extract and return it.
    if title_search:
        return title_search.group(1)
    return ""

# Apply the function to create a new 'Title' column
df_feature_eng['Title'] = df_feature_eng['Name'].apply(get_title)

# Display the counts of each title to see their distribution
print("Title distribution before mapping:")
print(df_feature_eng['Title'].value_counts())

# Map rare titles to a common 'Rare' category to reduce dimensionality
df_feature_eng['Title'] = df_feature_eng['Title'].replace(['Lady', 'Countess','Capt', 'Col',
    'Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')

df_feature_eng['Title'] = df_feature_eng['Title'].replace('Mlle', 'Miss')
df_feature_eng['Title'] = df_feature_eng['Title'].replace('Ms', 'Miss')
df_feature_eng['Title'] = df_feature_eng['Title'].replace('Mme', 'Mrs')

print("\nTitle distribution after mapping:")
print(df_feature_eng['Title'].value_counts())

# Display the first few rows with the new 'Title' column
display(df_feature_eng[['Name', 'Title']].head())

"""### Feature Engineering: Creating Family Size and IsAlone Features

Next, let's create a `FamilySize` feature by combining `SibSp` (siblings/spouses aboard) and `Parch` (parents/children aboard), and then derive an `IsAlone` feature to indicate if a passenger was traveling alone.
"""

# Create FamilySize feature
df_feature_eng['FamilySize'] = df_feature_eng['SibSp'] + df_feature_eng['Parch'] + 1 # +1 for the passenger themselves

# Create IsAlone feature
df_feature_eng['IsAlone'] = 0
df_feature_eng.loc[df_feature_eng['FamilySize'] == 1, 'IsAlone'] = 1

print("FamilySize distribution:")
print(df_feature_eng['FamilySize'].value_counts())
print("\nIsAlone distribution:")
print(df_feature_eng['IsAlone'].value_counts())

display(df_feature_eng[['SibSp', 'Parch', 'FamilySize', 'IsAlone']].head())

"""### Re-running the Full Data Preparation Pipeline with New Features

Now that we have new features (`Title`, `FamilySize`, `IsAlone`), we need to integrate them into our data preparation pipeline. This involves dropping original categorical columns (`Sex`, `Embarked`, `Name`, `Ticket`, `PassengerId`) and the `Cabin` column again, then creating dummy variables for our new `Title` column, along with `Sex` and `Embarked`, before concatenating them all back into our DataFrame. Finally, we'll re-split the data and re-train the model.
"""

# Drop the 'Cabin' column as it has too many missing values
df_feature_eng.drop('Cabin', axis=1, inplace=True)

# Create dummy variables for 'Sex', 'Embarked', and the new 'Title' column
sex_dummies_fe = pd.get_dummies(df_feature_eng['Sex'], drop_first=True, dtype=int)
embark_dummies_fe = pd.get_dummies(df_feature_eng['Embarked'], drop_first=True, dtype=int)
title_dummies_fe = pd.get_dummies(df_feature_eng['Title'], drop_first=True, dtype=int)

# Drop the original categorical columns and non-useful identifier columns
df_feature_eng.drop(['Sex', 'Embarked', 'Name', 'Ticket', 'PassengerId', 'Title'], axis=1, inplace=True)

# Concatenate the new dummy variables and engineered features to the DataFrame
df_feature_eng = pd.concat([df_feature_eng, sex_dummies_fe, embark_dummies_fe, title_dummies_fe], axis=1)

# Verify that there are no remaining NaN values in the features
print("Missing values after new feature engineering and cleaning:")
print(df_feature_eng.isnull().sum())

display(df_feature_eng.head())

"""### Re-splitting the Data and Re-training the Model

With our newly engineered features, we'll now re-split the data into training and testing sets and then re-train the Logistic Regression model to see if our changes have improved accuracy.
"""

# Re-perform train-test split with the new, feature-engineered DataFrame
X_fe = df_feature_eng.drop('Survived', axis=1)
y_fe = df_feature_eng['Survived']

X_train_fe, X_test_fe, y_train_fe, y_test_fe = train_test_split(X_fe, y_fe, test_size=0.30, random_state=101)

print("X_train_fe shape:", X_train_fe.shape)
print("y_train_fe shape:", y_train_fe.shape)
print("X_test_fe shape:", X_test_fe.shape)
print("y_test_fe shape:", y_test_fe.shape)

# Re-train the Logistic Regression model with the new feature-engineered data
logmodel_fe = LogisticRegression(max_iter=1000)
logmodel_fe.fit(X_train_fe, y_train_fe)

# Make predictions with the re-trained model
predictions_fe = logmodel_fe.predict(X_test_fe)

print("Model re-trained and predictions made.")

"""### Re-evaluating the Model with Feature-Engineered Data

Let's check the accuracy, classification report, and confusion matrix for our model with the newly engineered features.
"""

print("Accuracy Score with Feature Engineering:")
print(accuracy_score(y_test_fe, predictions_fe))

print("\nClassification Report with Feature Engineering:")
print(classification_report(y_test_fe, predictions_fe))

accuracy_fe = confusion_matrix(y_test_fe, predictions_fe)

plt.figure(figsize=(6, 4))
sns.heatmap(accuracy_fe, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No', 'Predicted Yes'],
            yticklabels=['Actual No', 'Actual Yes'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (with Feature Engineering)')
plt.show()

"""### Exploring a New Model: Random Forest Classifier

Let's try a more robust model, the Random Forest Classifier, which is an ensemble learning method that can often provide better accuracy and handle non-linear relationships in the data.
"""

from sklearn.ensemble import RandomForestClassifier

# Initialize the Random Forest Classifier with some default parameters
# (we can tune these later if needed)
rf_model = RandomForestClassifier(n_estimators=100, random_state=101, max_features='sqrt', min_samples_leaf=1, min_samples_split=2)

# Train the model on the feature-engineered training data
rf_model.fit(X_train_fe, y_train_fe)

print("Random Forest Classifier trained successfully.")

"""### Evaluating the Random Forest Model

Now, let's evaluate the performance of our newly trained Random Forest Classifier on the test set.
"""

# Make predictions with the Random Forest model
predictions_rf = rf_model.predict(X_test_fe)

# Evaluate the Random Forest model
print("Accuracy Score with Random Forest:")
print(accuracy_score(y_test_fe, predictions_rf))

print("\nClassification Report with Random Forest:")
print(classification_report(y_test_fe, predictions_rf))

accuracy_rf = confusion_matrix(y_test_fe, predictions_rf)

plt.figure(figsize=(6, 4))
sns.heatmap(accuracy_rf, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No', 'Predicted Yes'],
            yticklabels=['Actual No', 'Actual Yes'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Random Forest)')
plt.show()

"""### Addressing Convergence Warning: Feature Scaling and Re-tuning Logistic Regression

To address the `ConvergenceWarning` and potentially improve model stability and performance, we will scale our features using `StandardScaler` and then re-run `GridSearchCV`.
"""

from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and test data
X_train_scaled = scaler.fit_transform(X_train_fe)
X_test_scaled = scaler.transform(X_test_fe)

print("Features scaled successfully.")
# Display a snippet of the scaled data to confirm
print("\nFirst 5 rows of scaled X_train_fe:")
print(X_train_scaled[:5])

"""### Re-running GridSearchCV with Scaled Data

Now that our features are scaled, let's re-run `GridSearchCV` to find the best hyperparameters for the Logistic Regression model on this scaled data.
"""

# Re-define the parameter grid to search (can adjust if needed, but keeping same for direct comparison)
param_grid_scaled = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs', 'saga'],
    'max_iter': [2000] # Increased max_iter to give more room for convergence
}

# Create a Logistic Regression model instance
logmodel_grid_scaled = LogisticRegression()

# Create GridSearchCV object with scaled data
grid_search_scaled = GridSearchCV(logmodel_grid_scaled, param_grid_scaled, cv=5, verbose=1, scoring='accuracy', n_jobs=-1)

# Fit the GridSearchCV object to the scaled training data
grid_search_scaled.fit(X_train_scaled, y_train_fe)

# Print the best parameters and best score
print("\nBest Parameters found by GridSearchCV (Scaled Data):", grid_search_scaled.best_params_)
print("Best Cross-Validation Accuracy (Scaled Data):", grid_search_scaled.best_score_)

"""### Evaluating the Re-tuned Model with Scaled Data

Finally, let's evaluate the performance of the Logistic Regression model using the best parameters found with the scaled data on our scaled test set.
"""

# Get the best model from GridSearchCV (trained on scaled data)
best_logmodel_scaled = grid_search_scaled.best_estimator_

# Make predictions with the best model on the scaled test data
predictions_tuned_scaled = best_logmodel_scaled.predict(X_test_scaled)

# Evaluate the re-tuned model
print("Accuracy Score with Scaled & Tuned Model:")
print(accuracy_score(y_test_fe, predictions_tuned_scaled))

print("\nClassification Report with Scaled & Tuned Model:")
print(classification_report(y_test_fe, predictions_tuned_scaled))

accuracy_tuned_scaled = confusion_matrix(y_test_fe, predictions_tuned_scaled)

plt.figure(figsize=(6, 4))
sns.heatmap(accuracy_tuned_scaled, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No', 'Predicted Yes'],
            yticklabels=['Actual No', 'Actual Yes'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Scaled & Tuned Model)')
plt.show()

"""### Hyperparameter Tuning for Random Forest Classifier

Now, let's perform hyperparameter tuning for the `RandomForestClassifier` using `GridSearchCV`. This will help us find the best combination of parameters to optimize its performance on our feature-engineered and scaled data.
"""

from sklearn.ensemble import RandomForestClassifier

# Define the parameter grid for RandomForestClassifier
param_grid_rf = {
    'n_estimators': [100, 200, 300],
    'max_features': ['sqrt', 'log2'],
    'max_depth': [5, 10, None], # None means nodes are expanded until all leaves are pure or until all leaves contain less than min_samples_split samples.
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

# Create a RandomForestClassifier instance
rf_model_grid = RandomForestClassifier(random_state=101)

# Create GridSearchCV object
grid_search_rf = GridSearchCV(rf_model_grid, param_grid_rf, cv=5, verbose=1, scoring='accuracy', n_jobs=-1)

# Fit the GridSearchCV object to the scaled training data
grid_search_rf.fit(X_train_scaled, y_train_fe)

# Print the best parameters and best score
print("\nBest Parameters found by GridSearchCV for Random Forest:", grid_search_rf.best_params_)
print("Best Cross-Validation Accuracy for Random Forest:", grid_search_rf.best_score_)

"""### Evaluating the Tuned Random Forest Model

Let's evaluate the performance of the Random Forest model with the best parameters found by GridSearchCV.
"""

# Get the best Random Forest model from GridSearchCV
best_rf_model = grid_search_rf.best_estimator_

# Make predictions with the best Random Forest model on the scaled test data
predictions_rf_tuned = best_rf_model.predict(X_test_scaled)

# Evaluate the tuned Random Forest model
print("Accuracy Score with Tuned Random Forest Model:")
print(accuracy_score(y_test_fe, predictions_rf_tuned))

print("\nClassification Report with Tuned Random Forest Model:")
print(classification_report(y_test_fe, predictions_rf_tuned))

accuracy_rf_tuned = confusion_matrix(y_test_fe, predictions_rf_tuned)

plt.figure(figsize=(6, 4))
sns.heatmap(accuracy_rf_tuned, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No', 'Predicted Yes'],
            yticklabels=['Actual No', 'Actual Yes'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Tuned Random Forest Model)')
plt.show()

"""### Exploring a New Model: XGBoost Classifier

Let's try a Gradient Boosting model, specifically XGBoost, known for its high performance and efficiency.
"""

from xgboost import XGBClassifier

# Initialize the XGBoost Classifier
# Using some reasonable default parameters, can be tuned later
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=101)

# Train the model on the scaled and feature-engineered training data
xgb_model.fit(X_train_scaled, y_train_fe)

print("XGBoost Classifier trained successfully.")

"""### Evaluating the XGBoost Model

Now, let's evaluate the performance of our newly trained XGBoost Classifier on the test set.
"""

# Make predictions with the XGBoost model
predictions_xgb = xgb_model.predict(X_test_scaled)

# Evaluate the XGBoost model
print("Accuracy Score with XGBoost:")
print(accuracy_score(y_test_fe, predictions_xgb))

print("\nClassification Report with XGBoost:")
print(classification_report(y_test_fe, predictions_xgb))

accuracy_xgb = confusion_matrix(y_test_fe, predictions_xgb)

plt.figure(figsize=(6, 4))
sns.heatmap(accuracy_xgb, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No', 'Predicted Yes'],
            yticklabels=['Actual No', 'Actual Yes'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (XGBoost)')
plt.show()

"""### Hyperparameter Tuning for XGBoost Classifier

Now, let's fine-tune the XGBoost Classifier using `GridSearchCV` to find the optimal combination of hyperparameters for our dataset.
"""

from xgboost import XGBClassifier

# Define the parameter grid for XGBoost Classifier
param_grid_xgb = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'subsample': [0.7, 0.8, 0.9],
    'colsample_bytree': [0.7, 0.8, 0.9]
}

# Create an XGBClassifier instance
xgb_model_grid = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=101)

# Create GridSearchCV object
grid_search_xgb = GridSearchCV(xgb_model_grid, param_grid_xgb, cv=5, verbose=1, scoring='accuracy', n_jobs=-1)

# Fit the GridSearchCV object to the scaled training data
grid_search_xgb.fit(X_train_scaled, y_train_fe)

# Print the best parameters and best score
print("\nBest Parameters found by GridSearchCV for XGBoost:", grid_search_xgb.best_params_)
print("Best Cross-Validation Accuracy for XGBoost:", grid_search_xgb.best_score_)

"""### Evaluating the Tuned XGBoost Model

Let's evaluate the performance of the XGBoost model with the best parameters found by GridSearchCV.
"""

# Get the best XGBoost model from GridSearchCV
best_xgb_model = grid_search_xgb.best_estimator_

# Make predictions with the best XGBoost model on the scaled test data
predictions_xgb_tuned = best_xgb_model.predict(X_test_scaled)

# Evaluate the tuned XGBoost model
print("Accuracy Score with Tuned XGBoost Model:")
print(accuracy_score(y_test_fe, predictions_xgb_tuned))

print("\nClassification Report with Tuned XGBoost Model:")
print(classification_report(y_test_fe, predictions_xgb_tuned))

accuracy_xgb_tuned = confusion_matrix(y_test_fe, predictions_xgb_tuned)

plt.figure(figsize=(6, 4))
sns.heatmap(accuracy_xgb_tuned, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No', 'Predicted Yes'],
            yticklabels=['Actual No', 'Actual Yes'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Tuned XGBoost Model)')
plt.show()

"""### Hyperparameter Tuning with GridSearchCV

Now, let's use `GridSearchCV` to find the optimal hyperparameters for our `LogisticRegression` model. This helps in fine-tuning the model for better performance.
"""

from sklearn.model_selection import GridSearchCV

# Define the parameter grid to search
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs', 'saga'],
    'max_iter': [1000]
}

# Create a Logistic Regression model instance
logmodel_grid = LogisticRegression()

# Create GridSearchCV object
grid_search = GridSearchCV(logmodel_grid, param_grid, cv=5, verbose=1, scoring='accuracy', n_jobs=-1)

# Fit the GridSearchCV object to the training data (with feature engineering)
grid_search.fit(X_train_fe, y_train_fe)

# Print the best parameters and best score
print("\nBest Parameters found by GridSearchCV:", grid_search.best_params_)
print("Best Cross-Validation Accuracy:", grid_search.best_score_)

"""### Evaluating the Tuned Model

Let's evaluate the performance of the Logistic Regression model with the best parameters found by GridSearchCV.
"""

# Get the best model from GridSearchCV
best_logmodel = grid_search.best_estimator_

# Make predictions with the best model
predictions_tuned = best_logmodel.predict(X_test_fe)

# Evaluate the tuned model
print("Accuracy Score with Tuned Model:")
print(accuracy_score(y_test_fe, predictions_tuned))

print("\nClassification Report with Tuned Model:")
print(classification_report(y_test_fe, predictions_tuned))

accuracy_tuned = confusion_matrix(y_test_fe, predictions_tuned)

plt.figure(figsize=(6, 4))
sns.heatmap(accuracy_tuned, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No', 'Predicted Yes'],
            yticklabels=['Actual No', 'Actual Yes'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Tuned Model)')
plt.show()